### ISSUE TITLE
Kameleon does not work with Ruby 3.2

### ISSUE THREAD

**Issue by jonglezb** [oar-team/kameleon#128]
To reproduce the issue:

```bash
# docker run -it ruby:3.2 /bin/bash
# ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
# gem install --no-document kameleon-builder
# kameleon template list
kameleon template list
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/usr/local/bundle/gems/kameleon-builder-2.10.10/lib/kameleon.rb:43:in `userdir': undefined method `exists?' for File:Class (NoMethodError)

      Dir.mkdir(File.expand_path(@userdir.to_s)) unless File.exists?(File.expand_path(@userdir.to_s))
                                                            ^^^^^^^^
Did you mean?  exist?
```

**Comment by npf** [comment]
This is fixed in 2.10.12.
